# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Provider-Encoding
version:      0.10
version_from: lib/Template/Provider/Encoding.pm
installdirs:  site
requires:
    Encode:                        1
    Template:                      2.1
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
